name: ehpc.io CI

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE: ghcr.io/${{ github.repository }}
  CARGO_TERM_COLOR: always
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: "package.json"

      - name: Cache bun deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: bun-${{ runner.os }}-${{ hashFiles('bun.lock') }}
          restore-keys: |
            bun-${{ runner.os }}-

      - name: Install JS deps
        run: bun install --frozen-lockfile

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Cache cargo deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry
            ~/.cargo/git
            wasm/target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Install WASM deps
        run: curl https://drager.github.io/wasm-pack/installer/init.sh -sSf | bash -s -- -y

      - name: Run WASM tests
        run: bun test:wasm

      - name: Build WASM
        run: bun build:wasm

      - name: Lint js
        run: |
          bun run lint

      - name: Run js tests
        run: bun test

  build_and_push:
    if: github.event_name == 'push'
    needs: [lint_and_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Read package.json version
        id: version
        run: echo "version=v$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"

      - name: Build image
        run: |
          podman build \
            --pull=always \
            --build-arg APP_VERSION="${{ steps.version.outputs.version }}" \
            --tag $IMAGE:sha-${{ github.sha }} \
            .

      - name: Push sha image
        run: podman push $IMAGE:sha-${{ github.sha }}

      - name: Push prod image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          podman tag $IMAGE:sha-${{ github.sha }} $IMAGE:${{ github.ref_name }}
          podman push $IMAGE:${{ github.ref_name }}

          podman tag $IMAGE:${{ github.ref_name }} $IMAGE:prod
          podman push $IMAGE:prod
